name: Java CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: examo-backend/examo-backend
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: sri1708
          MYSQL_DATABASE: examo_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root -psri1708"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    
    env:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/examo_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: sri1708
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      
      - name: Wait for MySQL to be ready
        run: |
          echo "Waiting for MySQL to be ready..."
          for i in {1..30}; do
            if mysqladmin ping -h 127.0.0.1 -P 3306 -u root -psri1708 --silent; then
              echo "✅ MySQL is ready!"
              break
            fi
            echo "⏳ MySQL not ready yet. Attempt $i/30"
            sleep 2
          done

      - name: Verify database connection
        run: |
          mysql -h 127.0.0.1 -P 3306 -u root -psri1708 -e "SHOW DATABASES;"
      
      # Run tests excluding Selenium/UI tests
      - name: Run unit and integration tests (excluding Selenium)
        run: mvn test -Dtest='!*Selenium*,!*UI*,!*UITest*,!LoginUITest'



    
        # NEW STEP: SonarQube Analysis
   
      - name: SonarQube Analysis
        env:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} 
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
        run: |
            mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
              -Dsonar.projectKey=Srivaxshana_Examo_QA \
              -Dsonar.organization=srivaxshana \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.qualitygate.wait=false   
          
      - name: Build package
        run: mvn -B -DskipTests package
      
      - name: Upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: backend-test-reports
          path: |
            target/surefire-reports/
            target/cucumber-reports/

  build-frontend:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: examo-frontend
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: examo-frontend/package-lock.json
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build frontend
        run: CI=false npm run build
      
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: examo-frontend/dist/
